---
- name: Deploy application to Kubernetes
  hosts: master
  vars:
    destination: /home/ubuntu/drupal-kube
    source: /var/lib/jenkins/workspace/drupal-kube

  tasks:

    - name: Copy files from source to destination
      copy:
        src: "{{ source }}"
        dest: /home/ubuntu
        mode: '0644'

    - name: Make the deploy script executable
      file:
        path: "{{ destination }}/scripts/deploy.sh"
        mode: '0755'

    - name: Execute the deploy script
      shell: "{{ destination }}/scripts/deploy.sh"

