apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: drupal-namespace
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:10
        env:
        - name: DRUPAL_DATABASE_HOST
          value: postgres
        - name: DRUPAL_DATABASE_NAME
          value: drupaldb
        - name: DRUPAL_DATABASE_USER
          value: drupal
        - name: DRUPAL_DATABASE_PASSWORD
          value: drupalpassword
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites/default/files
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
  namespace: drupal-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi