apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: drupal-namespace
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: postgres
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: drupal-namespace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30091
  selector:
    app: phpmyadmin
